"""Assemble the production release package into .github-release/.

Pulls from two sources:
  - .github/          authoritative CI code (bmt package, actions, workflows)
  - scripts/release_templates/  files with no dev equivalent (trigger-ci.yml, actionlint.yaml)

Workflows in .github/workflows/ ship verbatim EXCEPT:
  - *-dev.yml files (dev-only; excluded by naming convention)
  - ops/ subdirectory (dev-only operational workflows)

Run via: just release
"""

from __future__ import annotations

import shutil
from pathlib import Path

REPO = Path(__file__).parent.parent
SRC = REPO / ".github"
TEMPLATES = Path(__file__).parent / "release_templates"
DEST = REPO / ".github-release"
SECRETS_SRC = REPO / "gcp" / "image" / "github" / "secrets"

EXCLUDE_ACTIONS = {"check-image-up-to-date"}
EXCLUDE_COPY = {"__pycache__", ".venv"}
EXCLUDE_WORKFLOW_DIRS = {"ops"}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _copy(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)


def _copy_tree(src: Path, dest: Path) -> None:
    for item in src.rglob("*"):
        if any(part in EXCLUDE_COPY for part in item.parts):
            continue
        if item.suffix == ".pyc":
            continue
        if item.is_file():
            _copy(item, dest / item.relative_to(src))


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    # 1. Clean destination
    if DEST.exists():
        shutil.rmtree(DEST)
    DEST.mkdir()

    # 2. Copy workflows: exclude *-dev.yml and ops/ subdirectory
    for wf in sorted((SRC / "workflows").glob("*.yml")):
        if wf.stem.endswith("-dev"):
            continue
        _copy(wf, DEST / "workflows" / wf.name)

    # 3. Copy workflow templates (production-specific files with no dev equivalent)
    for wf in sorted((TEMPLATES / "workflows").iterdir()):
        _copy(wf, DEST / "workflows" / wf.name)

    # 4. Copy actionlint config from templates
    _copy(TEMPLATES / "actionlint.yaml", DEST / "actionlint.yaml")

    # 5. Copy actions (exclude dev-only)
    for action_dir in sorted((SRC / "actions").iterdir()):
        if action_dir.name in EXCLUDE_ACTIONS:
            continue
        _copy(action_dir / "action.yml", DEST / "actions" / action_dir.name / "action.yml")

    # 6. Copy bmt package
    _copy_tree(SRC / "bmt" / "ci", DEST / "bmt" / "ci")
    _copy(SRC / "bmt" / "pyproject.toml", DEST / "bmt" / "pyproject.toml")
    _copy(SRC / "bmt" / "uv.lock", DEST / "bmt" / "uv.lock")
    _copy(SRC / "bmt" / "config" / "README.md", DEST / "bmt" / "config" / "README.md")

    # 7. Copy production GitHub App key
    _copy(
        SECRETS_SRC / "Kardome-org_core-main.pem",
        DEST / "bmt" / "config" / "secrets" / "Kardome-org_core-main.pem",
    )

    # 8. Write manifest
    workflow_names = sorted(p.name for p in (DEST / "workflows").iterdir())
    action_names = sorted(p.name for p in (DEST / "actions").iterdir())
    bmt_py_count = len(list((DEST / "bmt" / "ci").rglob("*.py")))

    (DEST / "RELEASE_MANIFEST.md").write_text(
        "# Release Package\n\n"
        "Generated by `just release`. **Do not edit manually.**\n\n"
        "## Sources\n\n"
        "| Content | Source |\n"
        "|---------|--------|\n"
        "| `workflows/` | `.github/workflows/*.yml` (excl. `*-dev.yml`, `ops/`) + `scripts/release_templates/workflows/` |\n"
        "| `actions/*/action.yml` | `.github/actions/` (`check-image-up-to-date` excluded) |\n"
        "| `bmt/ci/` | `.github/bmt/ci/` |\n"
        "| `bmt/config/secrets/Kardome-org_core-main.pem` | `gcp/image/github/secrets/` |\n"
        "| `actionlint.yaml` | `scripts/release_templates/actionlint.yaml` |\n\n"
        "## Deploy\n\n"
        "Copy contents of `.github-release/` into `kardome/core-main/.github/`.\n"
    )

    print(f"✓ Release package assembled → {DEST.relative_to(REPO)}/")
    print(f"  workflows : {len(workflow_names)} ({', '.join(workflow_names)})")
    print(f"  actions   : {len(action_names)}")
    print(f"  bmt/ci    : {bmt_py_count} .py files")


if __name__ == "__main__":
    main()
